"use client";

import { useState } from "react";
import { Dna, Megaphone, Sparkles } from "lucide-react";
import EnterWebsiteModal from "../components/EnterWebsiteModal";

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center relative overflow-hidden font-sans py-12">
      
      {/* Background Glowing Aura */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[600px] bg-lime-100/30 blur-[130px] rounded-full pointer-events-none" />

      <div className="relative z-10 w-full max-w-[1040px] px-6 flex flex-col items-center">
        
        {/* Top Header Logo */}
        <div className="text-lime-500 flex flex-col items-center justify-center mb-8">
          <svg width="44" height="44" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="drop-shadow-sm">
            <path d="M12 2L2 7L12 12L22 7L12 2Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            <path d="M2 17L12 22L22 17" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            <path d="M2 12L12 17L22 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </div>

        {/* Title Block */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 mb-4 tracking-tighter leading-[1.1]">
            Welcome to ScaleSoci
          </h1>
          <p className="text-[17px] text-gray-500 font-bold tracking-tight max-w-xl mx-auto leading-relaxed">
            Revolutionize your social media dynamic with automated, on-brand campaigns generated by AI.
          </p>
        </div>

        {/* 3 Step Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full mb-12 px-4 lg:px-0">
          
          {/* Card 1 */}
          <div 
            onClick={() => setIsModalOpen(true)}
            className="bg-white border border-gray-100 rounded-[3rem] p-10 flex flex-col items-center text-center cursor-pointer hover:shadow-2xl hover:-translate-y-2 transition-all group shadow-xl shadow-gray-200/50"
          >
            <div className="w-8 h-8 rounded-full bg-gray-50 text-gray-400 text-[11px] font-extrabold flex items-center justify-center mb-6 border border-gray-100">1</div>
            <h3 className="text-[20px] font-bold text-gray-900 mb-6 leading-tight">Generate<br/>Business DNA</h3>
            <div className="w-[100px] h-[100px] bg-lime-50 rounded-[2.2rem] flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-500 shadow-inner border border-lime-100">
              <Dna className="w-10 h-10 text-lime-500" strokeWidth={2} />
            </div>
            <p className="text-[13.5px] text-gray-500 leading-relaxed max-w-[190px] font-bold">
              Enter your website and we&apos;ll analyze every aspect of your brand.
            </p>
          </div>

          {/* Card 2 */}
          <div className="bg-white border border-gray-100 rounded-[3rem] p-10 flex flex-col items-center text-center shadow-xl shadow-gray-200/50">
            <div className="w-8 h-8 rounded-full bg-gray-50 text-gray-400 text-[11px] font-extrabold flex items-center justify-center mb-6 border border-gray-100">2</div>
            <h3 className="text-[20px] font-bold text-gray-900 mb-6 leading-tight">Tailored<br/>Campaign Ideas</h3>
            <div className="w-[100px] h-[100px] bg-sky-50 rounded-[2.2rem] flex items-center justify-center mb-6 shadow-inner border border-sky-100">
              <Megaphone className="w-10 h-10 text-sky-500" strokeWidth={2} />
            </div>
            <p className="text-[13.5px] text-gray-500 leading-relaxed max-w-[190px] font-bold">
              Use your Business DNA to fuel unique marketing strategies.
            </p>
          </div>

          {/* Card 3 */}
          <div className="bg-white border border-gray-100 rounded-[3rem] p-10 flex flex-col items-center text-center shadow-xl shadow-gray-200/50">
            <div className="w-8 h-8 rounded-full bg-gray-50 text-gray-400 text-[11px] font-extrabold flex items-center justify-center mb-6 border border-gray-100">3</div>
            <h3 className="text-[20px] font-bold text-gray-900 mb-6 leading-tight">High-Quality<br/>Creatives</h3>
            <div className="w-[100px] h-[100px] bg-purple-50 rounded-[2.2rem] flex items-center justify-center mb-6 shadow-inner border border-purple-100">
              <Sparkles className="w-10 h-10 text-purple-500" strokeWidth={2} />
            </div>
            <p className="text-[13.5px] text-gray-500 leading-relaxed max-w-[190px] font-bold">
              Download premium, on-brand visuals ready for distribution.
            </p>
          </div>

        </div>

        {/* Let's go Button */}
        <button 
          onClick={() => setIsModalOpen(true)}
          className="bg-lime-400 text-white px-16 py-5 rounded-full font-black text-[16px] hover:bg-lime-500 transition-all shadow-xl hover:shadow-lime-200 transform active:scale-95 uppercase tracking-widest"
        >
          Let&apos;s Get Started
        </button>

      </div>

      {isModalOpen && (
        <EnterWebsiteModal onClose={() => setIsModalOpen(false)} />
      )}
    </div>
  );
}
